############################################################
#
# Hide Media Players when not being used.
#
############################################################
  
############################################################
#
# Media Player Living Room Home
#
############################################################
  
# Hide Media Player

- alias: 'Hide media_player.living_room_home while not playing'
  hide_entity: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: media_player.living_room_home
    to: 'idle'
  - platform: state
    entity_id: media_player.living_room_home
    to: 'off'
  action:
  - service: group.set_visibility
    entity_id: group.media_living_room_home
    data:
      visible: False
# Show Media Player

- alias: 'Show media_player.office while playing'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: media_player.living_room_home
    to: 'playing'
  - platform: state
    entity_id: media_player.living_room_home
    to: 'paused'
  action:
  - service: group.set_visibility
    entity_id: group.media_living_room_home
    data:
      visible: True
############################################################
#
# Media Player Living Room TV
#
############################################################
  
# Hide Media Player

- alias: 'Hide media_player.tv_ua55ju6400 while not playing'
  hide_entity: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: media_player.tv_ua55ju6400
    to: 'idle'
  - platform: state
    entity_id: media_player.tv_ua55ju6400
    to: 'off'
  action:
  - service: group.set_visibility
    entity_id: group.media_living_room_tv
    data:
      visible: False
# Show Media Player

- alias: 'Show media_player.tv_ua55ju6400 while playing'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: media_player.tv_ua55ju6400
    to: 'playing'
  - platform: state
    entity_id: media_player.tv_ua55ju6400
    to: 'paused'
  action:
  - service: group.set_visibility
    entity_id: group.media_living_room_tv
    data:
      visible: True
############################################################
#
# Media Player Living Room
#
############################################################
  
# Hide Media Player

- alias: 'Hide media_player.living_room while not playing'
  hide_entity: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: media_player.living_room
    to: 'idle'
  - platform: state
    entity_id: media_player.living_room
    to: 'off'
  action:
  - service: group.set_visibility
    entity_id: group.media_living_room
    data:
      visible: False
# Show Media Player

- alias: 'Show media_player.living_room while playing'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: media_player.living_room
    to: 'playing'
  - platform: state
    entity_id: media_player.living_room
    to: 'paused'
  action:
  - service: group.set_visibility
    entity_id: group.media_living_room
    data:
      visible: True
############################################################
#
# Media Player Bed Room
#
############################################################
  
# Hide Media Player

- alias: 'Hide media_player.bed_room while not playing'
  hide_entity: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: media_player.bed_room
    to: 'idle'
  - platform: state
    entity_id: media_player.bed_room
    to: 'off'
  action:
  - service: group.set_visibility
    entity_id: group.media_bed_room
    data:
      visible: False
# Show Media Player

- alias: 'Show media_player.bed_room while playing'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: media_player.bed_room
    to: 'playing'
  - platform: state
    entity_id: media_player.bed_room
    to: 'paused'
  action:
  - service: group.set_visibility
    entity_id: group.media_bed_room
    data:
      visible: True
############################################################
#
# Media Player Outside
#
############################################################
  
# Hide Media Player

- alias: 'Hide media_player.outside while not playing'
  hide_entity: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: media_player.outside
    to: 'idle'
  - platform: state
    entity_id: media_player.outside
    to: 'off'
  action:
  - service: group.set_visibility
    entity_id: group.media_outside
    data:
      visible: False
# Show Media Player

- alias: 'Show media_player.outside while playing'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: media_player.outside
    to: 'playing'
  - platform: state
    entity_id: media_player.outside
    to: 'paused'
  action:
  - service: group.set_visibility
    entity_id: group.media_outside
    data:
      visible: True
############################################################
#
# Media Player Spotify
#
############################################################
  
# Hide Media Player

- alias: 'Hide media_player.spotify while not playing'
  hide_entity: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: media_player.spotify
    to: 'idle'
  - platform: state
    entity_id: media_player.spotify
    to: 'off'
  action:
  - service: group.set_visibility
    entity_id: group.media_spotify
    data:
      visible: False
# Show Media Player

- alias: 'Show media_player.spotify while playing'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: media_player.spotify
    to: 'playing'
  - platform: state
    entity_id: media_player.spotify
    to: 'paused'
  action:
  - service: group.set_visibility
    entity_id: group.media_spotify
    data:
      visible: True